eureka:
  client:
    remote-region-urls-with-name: http://localhost:8761/eureka/

server:
  port: 8765

spring:
  application:
    name: server-zuul

zuul:
  routes:
      api-a:
        path: /api-a/**
        serviceId: server-feign
      api-b:
        path: /api-b/**
        serviceId: server-ribbon
    #以/api-a/ 开头的请求都转发给service-feign服务
